general:
  kafka-topic: transactions

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

---
spring:
  config:
    activate:
      on-profile: test
  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers}

general:
  kafka-topic: test-transactions